# Mosquitto Configuration for Energy Thesis
listener 8883 0.0.0.0
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/mosquitto.crt
keyfile /mosquitto/certs/mosquitto.key
require_certificate true
use_identity_as_username true
allow_anonymous false

# Persistence
persistence true
persistence_location /mosquitto/data/

log_type all
