stages:
  preprocessing-interim:
    cmd: uv run computer-vision preprocessing interim
    deps:
      - ./data/1.raw/ECDUY/
      - ./src/computer_vision/preprocessing/interim.py
    outs:
      - ./data/2.interim/ECDUY/

  preprocessing-final:
    cmd: uv run computer-vision preprocessing final
    deps:
      - ./data/2.interim/ECDUY/
      - ./src/computer_vision/preprocessing/final.py
    outs:
      - ./data/3.final/ECDUY/

  plot:
    cmd: uv run computer-vision plot
    deps:
      - ./data/3.final/ECDUY/
      - ./src/computer_vision/plot.py
    outs:
      - ./imgs/

  evaluate:
    cmd: uv run computer-vision evaluate
    params:
      - general
      - models.${general.model}

    deps:
      - ./data/3.final/ECDUY/
      - ./src/computer_vision/evaluate.py
      - ./src/computer_vision/metrics.py
    # outs:
    #   - ./evaluate/model.pkl
    metrics:
      - ./eval/metrics.yaml
