general:
  fh: 24h
  model: cnn3d
  seed: 42
  cutoff: "2020-09-01T00:00:00-03:00"
  step: 96
  customer_ids:
    # MT 6.4 KV
    - 115138
    - 141844
    - 144453
    - 144472
    # MT 15 KV
    - 3904
    - 12530
    - 15805
    - 17454
    - 74310
    # MT 22 KV
    - 50176
    - 50201
    - 50227
    # MT 31.5 KV
    - 5082
    - 7001
    - 19100
    - 23573
    - 26397
    - 36307
    # MT 63 KV
    - 18052
    - 18389
    - 19810
    - 142540
models:
  cnn3d:
    epochs: 20
    batch_size: 32
    random_state: 42
    loss: mse
    metrics:
    optimizer: adam
    kernel_width: 1h
    dropout_rate: 0.2
    sample_weights_function:
    decay_rate: 0.01
    window_size: 168h

  naive:
    sp: 96
