general:
  fh: 24h
  model: darts_xgb
  seed: 42
  cutoff: '2020-09-01T00:00:00-03:00'
  step: 96
  customer_ids:
  - 115138
  - 3904
  - 50176
  - 7001
  - 18052
models:
  cnn3d:
    epochs: 200
    batch_size: 32
    random_state: 42
    loss: mse
    metrics:
    optimizer: adam
    kernel_width: 1h
    dropout_rate: 0.2
    sample_weights_function:
    decay_rate: 0.01
    window_size: 168h

  darts_xgb:
    lags: 96
    lags_past_covariates:
    output_chunk_length: 96
    random_state: 42
    multi_models: false

  naive:
    sp: 1

  lstm:
    loss: huber
    optimizer: adam
    random_seed: 42
    broadcasting: true
