version: "3.8"

tasks:
  certs:
    dir: ./architecture/after
    cmds:
      - ./generate_certs.sh

  architecture-before-up:
    dir: ./architecture/before
    cmds:
      - docker compose up -d
    deps: [build-meter]

  architecture-after-up:
    dir: ./architecture/after
    cmds:
      - docker compose up -d
    deps: [build-meter]

  build-meter:
    dir: ./packages/meter
    cmds:
      - docker build -t m.vinci/meter .

  build-forecaster:
    dir: .
    cmds:
      - docker build -t m.vinci/forecaster .
