version: "3.8"

tasks:
  certs:
    dir: ./architecture/after
    cmds:
      - ./generate_certs.sh

  architecture-before-up:
    dir: ./architecture/before
    cmds:
      - docker compose up -d --build
    deps: [build-meter]

  architecture-after-up:
    dir: ./architecture/after
    cmds:
      - docker compose up -d --build
    deps: [build-meter]

  build-meter:
    dir: ./packages/meter
    cmds:
      - docker build -t m.vinci/meter .

  build-forecaster:
    dir: .
    cmds:
      - docker build -t m.vinci/forecaster .

  run-forecast:
    dir: .
    cmds:
      - uv run computer-vision forecast
    env:
      FORECASTER_DB_HOST: localhost
      FORECASTER_DB_PORT: 5432
      FORECASTER_DB_DATABASE: postgres
      FORECASTER_DB_USER: modello-cnn3d
      FORECASTER_DB_PASSWORD: modello-cnn3d
      FORECASTER_DB_SSLROOTCERT: ./architecture/after/certs/ca.crt
      FORECASTER_DB_SSLCERT: ./architecture/after/certs/modello-cnn3d.crt
      FORECASTER_DB_SSLKEY: ./architecture/after/certs/modello-cnn3d.key
      FORECASTER_MODEL_PATH: ./output/train/cnn3d.zip
