# cat grafana.conf

[req]
distinguished_name = req_distinguished_name
req_extensions = req_ext
prompt = no

[req_distinguished_name]
C  = XX
ST = State
L  = City
O  = Academic Project
OU = Security Team
CN = grafana

[req_ext]
subjectAltName = @alt_names

[alt_names]
IP.1  = 127.0.0.1
DNS.1 = grafana
DNS.2 = localhost