# Mosquitto Configuration for Energy Thesis
listener 1883 0.0.0.0
password_file /mosquitto/config/passwd

allow_anonymous false

# Persistence
persistence true
persistence_location /mosquitto/data/

log_type all
